### ISSUE TITLE
Local demo service not working

### ISSUE THREAD

**Issue by bgorkem** [HadoukenIO/fdc3-service#211]
I am using node v12.3.1 (npm v6.13.4)
When I install the package and run `npm start` on the command line

I can see the FDC3 Service window and Launcher window.

However when I check the FDC3 Service Provider Debugger log I get this error: 
`contextChannels.ts:274 Unable to register client channel context handlers. getServicePromise() rejected with reason: Error: Trying to connect to provider from provider`

`index.ts:78 Channel not found for channelName: resolver, waiting for channel creation.`

I suspect Resolver initialisation is failing.

Any app I open ( charts, blotter ..) fail to communicate with fdc3-service  channel
`index.ts:78 Channel not found for channelName: of-fdc3-service-v1, waiting for channel creation.`

**Comment by ottah** [comment]
Are you running the demo on a Mac or Linux system?

**Comment by bgorkem** [comment]
Yes My OS is: MacOS Catalina 10.15.3.

**Comment by ottah** [comment]
The current stable runtime doesn't support an API call on Mac which is causing it to hang. The beta runtime 15.80.49.30 fixes this problem.

`npm start -- --runtime 15.80.49.30`

If you run the above command it should now work.

**Comment by bgorkem** [comment]
Yes confirmed it works with Mac, thanks!
